[package]
name = "rusws"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["full"]}
macros = {path = "./macros"}
utils = {path = "./utils"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctor = "0.1"